### ISSUE TITLE
Channel Overhaul

### ISSUE THREAD

**Issue by db2k** [Devcord/community#1]
Discord user **AlphaStyle** thought about improving the channel naming. Here are his proposes.

* #feedback => #devcord-feedback / #devcord-requests
* #i-need-help/#i-am-learning => combine both channels into one
* #links/#articles => combine them together
* #servers and #express => combine them since express is a server library
* #ui-design, #graphic-design, #logo-design => #webdesign or #graphic-design
* #support => #ask-a-moderator

---

I agree with some of them but I would like to discuss this first.

**Comment by thorerik** [comment]
#express would be more suited in #javascript, or if you want to split out backend and frontend, why not #frontnend-js and #backend-js? #servers, to me, is more on the lower levels of the stack (ie. OS, Apache, Nginx, harware, etc.).

**Comment by db2k** [comment]
True, good idea about the frontend-js and backend-js note.

**Comment by AlphaStyle** [comment]
**All of this are only my opinions and I would like to discuss it further!**

We did already try frontend and backend (*I know it's not what you suggested, only writing this to inform others :)* ) and it didn't work out because those two categories are so big they will include **everything** related to it's name. If you're not reading the channel for 10 minutes you won't be able to follow, and people can have multiple discussions at the same time which kinda force people to use **mention** so they can keep track of each others comments related to his/her questions.

When it come to the backend-js and frontend-js suggestion I think it can be confusing, because who are going to determen what is backend and frontend related? I know this question can look silly, but there are tools / libraries that can be used for both front- and backend. I know it's not the end of the world if someone type something frontend related in backend-js channel, I'm only saying I think it's more **clear** if we have a **#javascript** and **#servers** channel.

I do agree **#express** could in theory be talked about in **#javascript**, but I also think it can be talked about in **#servers** channel as well.

Express.js is build with [Node.js](https://en.wikipedia.org/wiki/Node.js) and Node.js itself is written in C++.
> Node.js is an Event-driven I/O server-side JavaScript environment based on Google Chrome's JavaScript Engine (V8 Engine). Although Node.js is not a JavaScript framework, many of its basic modules are written in JavaScript, and developers can write new modules in JavaScript. The runtime environment interprets JavaScript using Google's V8 JavaScript engine.

There are so many different [types of servers](https://en.wikipedia.org/wiki/Server_(computing)#Purpose), but because this is a web development discord server I will focus on **[web servers](https://en.wikipedia.org/wiki/Web_server)**.
> A web server is a computer system that processes requests via HTTP, the basic network protocol used to distribute information on the World Wide Web. The term can refer to the entire system, or specifically to the software that accepts and supervises the HTTP requests. The primary function of a web server is to store, process and deliver web pages to clients.

I would say everything that is involved into serving the said web page can fall under the **#servers** channel. *(containers, load balancers, operative systems, hardware, etc..)*

**Comment by db2k** [comment]
I guess maybe we can't have a topic related channel for **everything**. I also agree that Express can be discussed in #servers but also in #javascript. Maybe we drop the channel and people can decide where to talk about it?

I would like to keep the channels as pinpointed as possible to make sure everyone knows whats going on inside.

**Comment by AlphaStyle** [comment]
## What should we remove, edit or add?

**#welcome**
This channel is good for new people joining (info, rules, etc).

**#announcements**
Great for important information.

**#feedback** (*rename E.g **#devcord-request***)
Discuess improvements related to devcord. 

**#smalltalk**
general chit talk.

**#html** (*HTML and CSS do walk hand in hand, should they be merged?*)
HTML related.

**#css** 
CSS related.

**#javascript** (*There are alot of JavaScript questions so I think this should be as it is*)
JavaScript related.

**#php** (*There are alot of PHP questions so I think this should be as it is*)
PHP related.

**#other-languages** (*I would love this to be split into **many** sub channels when grouping is possible*)
Every language that does **not** have it's own channel.

**#electron-nwjs**
Cross-platform desktop applications.

**#servers**
Server related.

**#database**
Database related.

**#express** (*maybe delete, and use #javascript instead?*)
Express.js library related.

**#webpack** (*rename E.g **#module-bundlers** so it's not **webpack** specific*)
Webpack related | *or module bundlers related*.

**#security**
Security related.

**#ui-design** (*maybe merge ui, grapich and logo into one channel?*)
ui-design related.

**#grapich-design**
grapich-design related.

**#logo-design**
logo-design related.

**#soe**
SEO related.

**#give-me-the-feeback**
Show your work and get rated with constructive feeback.

**#i-need-help** (*merge i-am-learning with i-need-help and call it **#help** ?*)
If you need help this is the channel to ask.

**#i-am-learning**
not 100% sure the use case for this channel?

**#offtopic**
everything that is not relevant with web development and/or do not have it's own channel.

**#jobs**
looking for a job or to hire someone?

**#devrant**
development humor.

**#articles** (*maybe merge with links?*)
Links to good resources and/or good information.

**#links**
You have a link to share? Post it here!

**#support** (*rename E.g **#ask-a-moderator***)
In need of a moderator/admin? Report something? Question regarding Devcord?

**#bot-commands**
If you're going to write a bot command, please use this channel.

**Comment by thorerik** [comment]
I'm just curious if #seo is that useful, few if ever post in it, and whats been asked could easily been asked in #i-need-help (or #help).

**Comment by AlphaStyle** [comment]
I agree! **#i-need-help** even have this great pinned message made by Phil with **Helpful Links**. A SEO link could be added as well!

**Comment by db2k** [comment]
## New Proposal

Note that server related channels are prefixed with **underscores**

### Community Channels

**#_announcements**
Announcements, news and votings related to the server.

**#_intro**
Introduction Server for new users visiting the server.

**#_botcommands**
Channel for bot commands without other discussion

**#_support**
Support channel for server and community related questions

**#_feedback**
Feedback channel fetching updates from Github

**#_jobs**
Channel for job requests or recruiting

**#_devrant**
Ranting about all your problems and having general fun

**#_smalltalk**
Offtopic channel for general chat, memes and other discussions

### Development Channels

**#dev-html**
Channel for all document markup languages, also including templating languages

**#dev-styling**
Channel for CSS and all preprocessors related to CSS

**#dev-javascript**
Channel for Javascript and all related libraries like **React**, **Vue**, **Electron**, etc.

**#dev-php**
Channel for PHP and other PHP related content

**#dev-other**
Channel for all other languages and libraries (like Gulp, Webpack, etc.)

### Design Channels

**#design-graphics**
Channel for graphic design

**#design-ux**
Channel for UX/UI design

**#design-logo**
Channel for Logo design (since logos are a speciality in graphic design topics)

### System Channels

**#system-servers**
Channel for Server discussions (Apache, Express, Nginx)

**#system-database**
Channel for database related discussions (MongoDB, MySQL, etc.)

**#system-security**
Channel for security related discussions

### Web Channels

**#web-seo**
SEO related discussions

**#web-articles**
Blog articles & news which could be interesting

**#web-tools**
Cool software and websites you're using for work and other usecases


---

**New Channellist**

* #_announcements
* #_intro
* #_botcommands
* #_support
* #_feedback
* #_jobs
* #_devrant
* #_smalltalk
* #dev-html
* #dev-styling
* #dev-javascript
* #dev-php
* #dev-other
* #design-graphic
* #design-ux
* #design-logo
* #system-servers
* #system-database
* #system-security
* #web-seo
* #web-articles
* #web-tools

---

What do you think?

**Comment by db2k** [comment]
Nevermind underscores can't be used as first characters. :/
